# -*- coding: utf-8 -*-
"""HTML_QUICK_STYLER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVCdt_95Y31ZjmIhajySnyX5JPP1ba3g
"""

!pip install gradio --upgrade --quiet

import gradio as gr

# ===============================
# COLOR THEMES
# ===============================

def get_colors(style):
    themes = {
        "modern": {
            "primary": "#6366f1",
            "background": "#0f172a",
            "text": "#ffffff"
        },
        "ocean": {
            "primary": "#0077b6",
            "background": "#03045e",
            "text": "#caf0f8"
        }
    }
    return themes.get(style, themes["modern"])


# ===============================
# WEBSITE GENERATOR FUNCTION
# ===============================

def generate_website(title, description, style):

    colors = get_colors(style)

    html = f"""
    <html>
    <head>
    <style>
        body {{
            margin:0;
            font-family: Arial;
            background:{colors['background']};
            color:{colors['text']};
        }}

        header {{
            background:{colors['primary']};
            padding:60px;
            text-align:center;
        }}

        section {{
            padding:40px;
        }}

        footer {{
            background:{colors['primary']};
            padding:20px;
            text-align:center;
        }}
    </style>
    </head>

    <body>

        <header>
            <h1>{title}</h1>
            <p>{description}</p>
        </header>

        <section>
            <h2>Features</h2>
            <ul>
                <li>Responsive Design</li>
                <li>Modern Layout</li>
                <li>Fast Performance</li>
            </ul>
        </section>

        <section>
            <h2>About</h2>
            <p>This website is generated using HTML Quick Styler.</p>
        </section>

        <section>
            <h2>Contact</h2>
            <p>Email: example@email.com</p>
        </section>

        <footer>
            © 2026 All Rights Reserved
        </footer>

    </body>
    </html>
    """

    return html


# ===============================
# GRADIO UI
# ===============================

with gr.Blocks() as app:

    gr.Markdown("# 🚀 HTML Quick Styler")

    title = gr.Textbox(label="Page Title")
    description = gr.Textbox(label="Description")
    style = gr.Dropdown(["modern", "ocean"], value="modern")

    generate_btn = gr.Button("Generate")

    output = gr.HTML()

    generate_btn.click(
        fn=generate_website,
        inputs=[title, description, style],
        outputs=output
    )

app.launch(share=True)